services:
  app:
    image: tnfshcec/web
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./cec/:/app/cec
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ORIGIN=http://localhost:3000
